### ISSUE TITLE
Add support for multi-attribute (4.5.5)

### ISSUE THREAD

**Issue by HoucemKacem** [stellio-hub/stellio-context-broker#101]
Support for multi-attributes should be added as follow:

- [x] Create and retrieve an entity Properties (entity service)
- [x] Update entity Properties (entity service)
- [x] Store distinct entries in search service (search service)
- [x] Create and retrieve an entity Relationships (entity service)
- [x] Append entity Properties (entity service)
- [x] Search for the temporal evolution of a given instance (search service)
- [x] Delete entity Properties (entity attributes)
- [x] Define the event model
- [x] Update entity Relationships (entity service)
- [x] Append entity Relationships (entity service)
- [x] Delete entity Relationships (entity attributes)
- [x] Partial update entity Attributes (entity service)
- [ ] Integration in subscription service for Properties (subscription service)
- [ ] Integration in subscription service for Relationships (subscription service)
- [ ] Create and retrieve an entity GeoProperties (entity service)
- [ ] Update entity GeoProperties (entity service)
- [ ] Append entity GeoProperties (entity service)
- [ ] Delete entity GeoProperties (entity attributes)
- [ ] Integration in subscription service for GeoProperties (subscription service)
- [ ] Integration in search service for GeoProperties (Search service)

**Comment by HoucemKacem** [comment]
@bobeal can we discuss the priorities ?

**Comment by bobeal** [comment]
Go for next iteration: support for relationships.
