### ISSUE TITLE
Problem with probes when starting subscription-service, under stressed conditions, request /actuator/health does not answer.

### ISSUE THREAD

**Issue by agaldemas-eridanis** [stellio-hub/stellio-context-broker#1019]
Hello, I have added, the probes readinessProbe and livenessProbe, to subscription-service (trhough a request /actuator/health)
OK when you start the service whithout activity. 
but when there is a lot of incoming traffic when starting a pod (meaning receiving many notifications to treat), the request `/actuator/health` is not responding, and then perturbating the deployment, as the probes does not work, the pod is restarted by kubernetes, I removed the probes, for the moment, 

But it means that it won't be possible to add HPA to the service for autoscaling...

May be it's a problem with routes priority in the service ?
at your disposal to discuss about this strange behaviour.

**Comment by bobeal** [comment]
Found this that seems closely related: https://github.com/spring-projects/spring-boot/issues/26367

First thing to do should probably to configure a specific port for the management server (which is currently not the case). Before looking at other options in the issue.

**Comment by agaldemas-eridanis** [comment]
OK, I'll try to add a port for Actuator service, 
if I can't manage, I'll come back to ask for help

**Comment by agaldemas-eridanis** [comment]
Hi again, I managed to add the management port on 8085, (through a variable : - name: MANAGEMENT_SERVER_PORT
          value: "8085", and a containerPort: 8085,
OK the port is open, but unfortunately still the request `curl http://localhost:8085/actuator/health' fails, with no answer...

Probably because of the out of memory error we have in parallel (see issue #1020) !

then it's dog biting its tail !

**Comment by agaldemas-eridanis** [comment]
Hello, @bobeal, I confirm the problem is related to memory error we have in subscription-service, 
once the error  : 

`An exception 'java.lang.OutOfMemoryError: Java heap space' [enable DEBUG level for full stacktrace] was thrown by a user handler's exceptionCaught() method while handling the following exception:
 java.lang.OutOfMemoryError: Java heap space`

occurs in a pod, the program is dead, so no answer to whatever request you try !, 
the only way is to add new pods, manually...
