### ISSUE TITLE
Issue with @ character in DateTime data types (@type and @value are refused)

### ISSUE THREAD

**Issue by JTrullier** [stellio-hub/stellio-context-broker#1027]
We are testing the behavior of the context broker with data types with @type and @value like *dateObserved* in the [AirQualityObserved Smart Data Model](https://fiware-datamodels.readthedocs.io/en/stable/ngsi-ld_howto/#example-of-migration-to-ngsi-ld). AirQualityObserved  have the following structure :
```json
{
    "id": "urn:ngsi-ld:AirQualityObserved:RZ:Obsv4567",
    "type": "AirQualityObserved",
    "dateObserved": {
        "type": "Property",
        "value": {
            "@type": "DateTime",
            "@value": "2018-08-07T12:00:00Z"
        }
    },
    "NO2": {
        "type": "Property",
        "value": 22,
        "unitCode": "GP"
    },
    "refPointOfInterest": {
        "type": "Relationship",
        "object": "urn:ngsi-ld:PointOfInterest:RZ:MainSquare"
    },
    "@context": [
        "https://schema.lab.fiware.org/ld/context",
        "https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context.jsonld"
    ]
}
```
### Stellio configurations

* 2.3 (OK with @ char)
* 2.8 (2.7 has the same issue)

### Testing with a similar entity in both environments

We create a dummy entity as follows :
```json
{
    "id": "urn:ngsi-ld:TestEntity:test1",
    "type": "TestEntity",
    "myDateField": {
        "value": {
            "@value": "2023-04-28T10:25:55.000Z",
            "@type": "DateTime"
        },
        "type": "Property"
    },
    "anotherField": {
        "type": "Property",
        "value": "irrelevant"
    },
    "@context": [
        "http://ld-context/hdp-context-ngsi.jsonld"
    ]
}
```

### In Stellio 2.3
The creation of this type of entity works fine.

### Stellio 2.8 (2.7)
The context broker returns an error 400 Bad Request saying that @value (or @type) are invalid characters.
```json
{
"detail": "The JSON-LD object contains a member with invalid characters (4.6.2): @value",
"type": "https://uri.etsi.org/ngsi-ld/errors/BadRequestData",
"title": "The request includes input data which does not meet the requirements of the operation"
}
```

If I try to remove the @ (on value and type), I get this :
```json
{
"detail": "Property https://uri.etsi.org/ngsi-ld/default-context/myDateField has an instance without a value",
"type": "https://uri.etsi.org/ngsi-ld/errors/BadRequestData",
"title": "The request includes input data which does not meet the requirements of the operation"
}
```

Is this the intended behavior?
Is the AirQualityObserved Smart Data Model deprecated in the docs and we shouldn't use *dateObserved* like this anymore? If this is the case, can you provide me an example of the new data model for DateTime attributes and orient me to patch notes saying that this format is deprecated?
```json
"dateObserved": {
    "type": "Property",
    "value": {
        "@type": "DateTime",
        "@value": "2018-08-07T12:00:00Z"
    }
}
```

Thank you very much !

@agaldemas-eridanis

**Comment by agaldemas-eridanis** [comment]
Sorry @JTrullier, I din't thought about that when we spoke together:

 I would say, '@' can't be deprecated, since @type & @value is still used in many data models...

More over '@' is not in the list of forbidden characters in NGSI-LD...

so I'm thinking more of a bug...

**Comment by agaldemas-eridanis** [comment]
I think I found the problem in DataRepresentationUtils.kt:
```
private fun String.isNgsiLdSupportedName(): Boolean =
    this.all { char -> char.isLetterOrDigit() || listOf(':', '_').contains(char) }
````
should be
```
private fun String.isNgsiLdSupportedName(): Boolean =
    this.all { char -> char.isLetterOrDigit() || listOf(':', '_','@').contains(char) }
````
and may be some other characters ?

I asked to Bing GPT to get an answer about ngsi-ld forbidden characters in names here is the summary of the answer:

The following characters are forbidden in NGSI-LD:

- Control characters
- Whitespace
- &
- ?
- /
- #


Hello @bobeal will you fix the issue on your side, or you prefer a PR ?

**Comment by bobeal** [comment]
The errors refers to 4.6.2, which is about allowed characters in Entity Type Names, Property Names and Relationship Names. The list of allowed characters is correct and must not be changed since it is defined by the specification.

The problem is that the current implementation also checks what is inside the `value` JSON object whereas it should not (it is entity content). Gonna fix it.
