### ISSUE TITLE
log level for api-gateway can't be limited to WARN, INFO messages still appear in the logs, need of another variable to control logging level

### ISSUE THREAD

**Issue by agaldemas-eridanis** [stellio-hub/stellio-context-broker#1060]
Hello, @bobeal, I didn't noticed, but if using the env variable `LOGGING_LEVEL_COM_EGM_STELLIO: WARN`, to limit com.egm.stellio loglevel to WARN, it apply well for search-service and subscription-service, but for api-gateway, we have still INFO level messages logging the incoming requests such as : 

`2023-12-04 15:00:00,339 [or-http-epoll-1] INFO  LoggingFilter                            - log - [5b058b4a-9, L:/10.42.185.124:53442 - R:search-service.hdp-stellio-2-3.svc.cluster.local/10.43.231.79:8083] READ: 15378B HTTP/1.1 200 OK`

logging every request coming into the component...., so my question is : 
is there a way to change this, with a variable such as: `LOGGING_LEVEL_COM_ORG_SPRINGFRAMEWORK: WARN`, in the configmap ?
which I tried, without effect on the LoggingFilter messages

thanks in advance for your help on this, because in production we absolutely need to hide those request logs for confidentiality...

**Comment by agaldemas-eridanis** [comment]
copy @JTrullier....

**Comment by agaldemas-eridanis** [comment]
OK, we have to upgrade, to last version, since we use 2.3.0, which does not use zalando logbook..., I have one almost ready to upgrade !

but how to set `logbook.filter.enabled` to false, from helm chart values file ?

with a variable `LOGBOOK_FILTER_ENABLE: false` in the Configmap ?

thanks in advance for your answer.

**Comment by bobeal** [comment]
Yes, `LOGBOOK_FILTER_ENABLED: false` should work (anyway, this is how it works when defined as Docker env variables)

**Comment by agaldemas-eridanis** [comment]
Hello, @bobeal, we have tried to upgrade to 2.9.0, and 2.10.0, but we had to come back to 2.3.0, because of an issue with subscription notifications, we'll issue an issue ;O), about the problem !
But we might go in production very soon, so needing a solution to remove INFO LoggingFilter messages, with 2.3.0 (which doesn't use Zalando Logbook), 
I tried to set `LOGGING_LEVEL_COM_ORG_SPRINGFRAMEWORK: WARN`, without success :(
then if you have a solution, you're welcome !

**Comment by bobeal** [comment]
Can you try these ones: https://github.com/stellio-hub/stellio-context-broker/blob/2.3.0/api-gateway/src/main/resources/logback-spring.xml#L33-L34 ?

**Comment by agaldemas-eridanis** [comment]
Hello I tried to add 2 variables in the stellio-configmap.yaml :
following the same rule as   LOGGING_LEVEL_COM_EGM_STELLIO: WARN : 
which works and limit the loglevel to WARN for the pod process (without changing the file logback.xml),  but with those 2 new variables (correctly added in deployment as a env coming from configmap)
  LOGGING_LEVEL_REACTOR_NETTY: WARN
  LOGGING_LEVEL_COM_ORG_SPRINGFRAMEWORK: WARN

the INFO LoggingFilter log messages are still there, so either the varables are not taken in count, or it's not the right filter
I tried also using a variable named LOGGING_LEVEL_COM_ORG_SPRINGFRAMEWORK_CLOUD_GATEWAY, without result :(

may be I can change the LoggingFilter log level  trough the spring management api
because I prefer not to build a new image, just to change logback.xml file...
but seems it miss the management endpoints for logging, once again to add this:
management.endpoints.web.exposure.include=loggers
management.endpoint.loggers.enabled=true
in application.properties, should I use the variable substitution ?
