### ISSUE TITLE
Refactor the expandedEntity validation 

### ISSUE THREAD

**Issue by HoucemKacem** [stellio-hub/stellio-context-broker#107]
Currently the process of validating an expandedEntity is done in several places (entityService, ExpandedEntity and NgsiLdParsingUtils).
A refactoring should be done to create a validation step.

**Comment by bobeal** [comment]
What validation covers:
- Payload is JSON-LD compliant (done via jsonld-java library)
- Payload is NGSI-LD compliant (it has an id, a type, no mixed properties and relationships, ...)
- Business checks: no existing entity with the same id, existence of relationships targets, ...
- Handle the special case of batch queries where validation implies more than one entity at the same time (especially for the relationships)

Implementation thoughts:
⁃ Composability of validation rules
⁃ Composability of parsing and validation
⁃ Composability of entity and list of entities (via a higher kind?) ?

Handling entities from events:
- We know entity is valid and we *may* need to deal with a parsed version of it without validating it again
- But, typically, we only need id and type of the entity (and we have them directly in the event)
- Actually, the only place we need this parsed version is to extract the location information
- So not a major concern right now but still a point to deal with

Entity rendering:
- It can be done via a JsonLdExpandedEntity structure (does not need a parsed and validated structure)

Misc related refactorings:
- Rename ExpandedEntity to NgsiLdEntity (and later have NgsiLdProperty, NgsiLdRelationship, ...)

**Comment by bobeal** [comment]
It has been globally done with enhancements since then.

At least, `NgsiLdEntity` brings (big) parts of this when parsing an incoming payload.

The tricky case of non existing targets has been resolved by allowing them.

Let's create a new, more focused issue if we spot new problems with existing validation.
