### ISSUE TITLE
Stellio Take so much time to execute temporal queries

### ISSUE THREAD

**Issue by Manifesto24** [stellio-hub/stellio-context-broker#1082]
Hello, 

I have around 148.000 entities in a Stellio context broker and I am trying to fetch some temporal data for a specific entity between a time range(e.g for a day). It seems that this queries take so much time to execute (50, 60 seconds maybe even more).

**Comment by bobeal** [comment]
Hello,

Temporal queries can take some time if you have a lot of historical data but 50 to 60 seconds is really long.

Can you give some more info about your context:
- Hardware configuration (CPU, RAM, ...)
- The (rough) number of historical instances of the entity
- The HTTP query
- Stellio version

**Comment by bobeal** [comment]
No details provided following my previous comment, closing the issue.
