### ISSUE TITLE
Requesting a large pagination limit should result in a TooManyResults error not BadRequest

### ISSUE THREAD

**Issue by jason-fox** [stellio-hub/stellio-context-broker#1137]
Stellio 2.12.1

 I have no entities and request with `limit` - `/entities/?type=TemperatureSensor&limit=1001`

Stellio Returns a **400 Bad Request** error code and:

```json
{
    "detail": "You asked for 1001 results, but the supported maximum limit is 100",
    "type": "https://uri.etsi.org/ngsi-ld/errors/BadRequestData",
    "title": "The request includes input data which does not meet the requirements of the operation"
}
```

According to the 1.8.1 spec this is **403 Forbidden** error of `type` `https://uri.etsi.org/ngsi-ld/errors/TooManyResults`

Note that 100 entities is very low compared to other brokers.

**Comment by bobeal** [comment]
> Note that 100 entities is very low compared to other brokers.

The default is low but it is configurable (although poorly documented...). 

@ranim-n can you also add some doc about this configuration:
- in https://stellio.readthedocs.io/en/latest/index.html (in this page: https://stellio.readthedocs.io/en/latest/admin/production_deployment.html ?)
- to make it easier for people to configure it, add the environment variables in the `.env` file and use them in the `docker-compose.yml` file provided in the repository
