### ISSUE TITLE
503 Error on POST Requests: LdContextNotAvailable in Stellio Context Broker

### ISSUE THREAD

**Issue by dr-yst** [stellio-hub/stellio-context-broker#1159]
Hello,

I'm new to Stellio.
I am currently following the API walkthrough provided in the [Stellio documentation](https://stellio.readthedocs.io/en/latest/API_walkthrough.html) and encountered an error while trying to post to the Beekeeper as the first step. Here's the error message I received:

```json
{
  "type": "https://uri.etsi.org/ngsi-ld/errors/LdContextNotAvailable",
  "title": "A remote JSON-LD @context referenced in a request cannot be retrieved by the NGSI-LD Broker and expansion or compaction cannot be performed",
  "status": 503,
  "detail": "Unable to load remote context (cause was: JsonLdError[code=There was a problem encountered loading a remote context [code=LOADING_REMOTE_CONTEXT_FAILED]., message=There was a problem encountered loading a remote context [code=LOADING_REMOTE_CONTEXT_FAILED].])",
  "instance": "/ngsi-ld/v1/entities"
}
```

I have ensured that all steps were accurately followed.
Could you please provide guidance on how I can proceed with the walkthrough despite this issue?
Is there a workaround or a specific configuration I should check?

Any guidance on how to resolve this would be greatly appreciated.

Thank you in advance for your assistance.

**Comment by lucboj** [comment]
Hello @dr-yst,

I think following PR is related to this: https://github.com/easy-global-market/ngsild-api-data-models/issues/205

Problem seems to be a broken link in the context. Once fixed your requests should run successfully.

**Comment by bobeal** [comment]
Hi @dr-yst,

As said by @lucboj, there was a broken link in the JSON-LD context used in the API Quickstart. The [PR](https://github.com/easy-global-market/ngsild-api-data-models/pull/206) has been merged, it should now work again.

**Comment by dr-yst** [comment]
@lucboj @bobeal 
Thank you very much for the prompt response and resolution!
I confirmed that everything is now working properly.
I really appreciate your help.
