### ISSUE TITLE
POST entityOperations/query not returning expected entities

### ISSUE THREAD

**Issue by junjou** [stellio-hub/stellio-context-broker#1250]
A post request on `/entityOperations/query` with this body:
```json
{
    "type": "Query",
    "entities": [
        {
            "id": "urn:ngsi-ld:Device:00078137000DCAE7",
            "type": "Device"
        },
        {
            "id": "urn:ngsi-ld:Device:0004A30B00EDB65B",
            "type": "Device"
        }
    ]
}
```

Is returning only the first entity.

**Comment by bobeal** [comment]
Indeed, known limitation to be adressed: Yes, known limitation in the current implementation: https://github.com/stellio-hub/stellio-context-broker/blob/develop/search-service/src/main/kotlin/com/egm/stellio/search/entity/util/EntitiesQueryUtils.kt#L72

**Comment by bobeal** [comment]
First thought: better option should be to enhance the query on entities to allow passing a list of OR conditions based on (id, type, idPattern)
