### ISSUE TITLE
'Property XXX has an instance without a value' when value is part of the payload

### ISSUE THREAD

**Issue by jason-fox** [stellio-hub/stellio-context-broker#158]
I am attempting to input the following using a [generated `@context`](https://raw.githubusercontent.com/FIWARE/tutorials.NGSI-LD/master/app/public/data-models/ngsi-context.jsonld)

```console
curl -L -X POST 'http://localhost:8080/ngsi-ld/v1/entities/' \
-H 'Content-Type: application/ld+json' \
-H 'Cookie: _csrf=MAPTGFPcoPnewsGCWklHi4Mq' \
--data-raw '{
    "id": "urn:ngsi-ld:Building:farm001",
    "type": "Building",
    "category": {
    	"type": "Property",
        "value": ["farm"]
    },
    "address": {
        "type": "Property",
        "value": {
            "streetAddress": "Großer Stern 1",
            "addressRegion": "Berlin",
            "addressLocality": "Tiergarten",
            "postalCode": "10557"
        },
        "verified": {
			"type": "Property",
			"value": true
		}
    },
    
    "location": {
        "type": "GeoProperty",
        "value": {
             "type": "Point",
             "coordinates": [13.3505, 52.5144]
        }
    },
    "name": {
        "type": "Property",
        "value": "Victory Farm"
    },
    "@context": [
        "https://raw.githubusercontent.com/FIWARE/tutorials.NGSI-LD/master/app/public/data-models/ngsi-context.jsonld",
        "https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context.jsonld" 
    ]
}'
```

Creating the Entity without an address works fine. However adding the `address` attribute causes the following error:

```json
{
    "detail": "Property https://schema.org/address has an instance without a value",
    "type": "https://uri.etsi.org/ngsi-ld/errors/BadRequestData",
    "title": "The request includes input data which does not meet the requirements of the operation"
}
```

However the property does exist in the request - it is a JSON Object.

**Comment by bobeal** [comment]
Indeed, this is currently not yet supported. To be planned.

**Comment by bobeal** [comment]
Use https://neo4j.com/labs/apoc/4.2/overview/apoc.convert/apoc.convert.setJsonProperty/ (and https://neo4j.com/labs/apoc/4.1/overview/apoc.convert/apoc.convert.getJsonProperty/ for querying inside the object)

**Comment by jason-fox** [comment]
@bobeal - since this is fixed, once you have tagged a docker release, could you raise a PR to add a Stellio `docker-compose` to the NGSI-LD Getting Started tutorial - https://github.com/FIWARE/tutorials.Getting-Started/tree/NGSI-LD/docker-compose

Once that is done I can add the necessary texts to incorporate Stellio as an option and start updating the other NGSI-LD tutorials as well.

**Comment by bobeal** [comment]
> @bobeal - since this is fixed, once you have tagged a docker release, could you raise a PR to add a Stellio `docker-compose` to the NGSI-LD Getting Started tutorial - https://github.com/FIWARE/tutorials.Getting-Started/tree/NGSI-LD/docker-compose
> 
> Once that is done I can add the necessary texts to incorporate Stellio as an option and start updating the other NGSI-LD tutorials as well.

Hi @jason-fox,

Sure, I will handle this!

However, we don't plan a new release before September (major upgrades going on). I'll maybe prepare a draft PR targeting the `dev` tagged Docker images of Stellio and make the switch to an official version when one is out.
