### ISSUE TITLE
Update neo4j config in k8s setup to load apoc plugin

### ISSUE THREAD

**Issue by bobeal** [stellio-hub/stellio-context-broker#194]
Our last migration script in entity-service required the apoc library to be loaded, which is done for docker-compose config (`NEO4JLABS_PLUGINS=["apoc"]`), but not k8s one.

Add the necessary similar config in `kubernetes/neo4j-deployment.yaml`.

**Comment by HoucemKacem** [comment]
I tried to provide the required env variables (as in docker-compose.yml) but there were an error in parsing the value of NEO4JLABS_PLUGINS: ["apoc"] 
I think we should either:
-  Use [init containers](https://kubernetes.io/fr/docs/concepts/workloads/pods/init-containers/)
-  Build a custom docker image of Neo4j which layers the plugins on top it.

**Comment by bobeal** [comment]
> I tried to provide the required env variables (as in docker-compose.yml) but there were an error in parsing the value of NEO4JLABS_PLUGINS: ["apoc"] 
> 
> 
> 
> I think we should either:
> 
> -  Use [init containers](https://kubernetes.io/fr/docs/concepts/workloads/pods/init-containers/)
> 
> -  Build a custom docker image of Neo4j which layers the plugins on top of it.   

What was the error?

**Comment by HoucemKacem** [comment]
With:
- env:
        - name: NEO4JLABS_PLUGINS
          value: "[apoc]"
`parse error: Invalid numeric literal at line 1, column 6`

And with:
- env:
        - name: NEO4JLABS_PLUGINS
          value: ["apoc"]
`error validating data: ValidationError(Deployment.spec.template.spec.containers[0].env[4].value): invalid type for io.k8s.api.core.v1.EnvVar.value: got "array", expected "string"`

**Comment by bobeal** [comment]
>     * NEO4JLABS_PLUGINS

Did you try such a notation: https://github.com/xclemence/dependencies-graph-chart/blob/f9e89531b221c08008b482ff41f2c7f598dfce85/dependencies-graph/templates/neo4j.yaml#L25?

(which looks similar to what is in https://github.com/helm/charts/blob/master/stable/neo4j/templates/core-configmap.yaml)
