### ISSUE TITLE
Add support for other GeoJSON geometries in Entity's location property

### ISSUE THREAD

**Issue by bobeal** [stellio-hub/stellio-context-broker#204]
GeoJSON geometries, as described in the Specification (4.10), can be one of the following types:

- [X] Point
- [ ] MultiPoint
- [ ] LineString
- [ ] MultiLineString
- [X] Polygon
- [ ] MultiPolygon

The library used currently for extracting/parsing geometry objects, supports all geometries types mentioned above, as described [here](https://locationtech.github.io/jts/javadoc/org/locationtech/jts/io/WKTReader.html).

**Comment by bobeal** [comment]
> @HoucemKacem do we still miss things on this?

@HoucemKacem no news?

**Comment by HoucemKacem** [comment]
We recently added support for Polygons, but there still other geometries to support, we can apply the same principle and store them in wkt format.

**Comment by bobeal** [comment]
> We recently added support for Polygons, but there still other geometries to support, we can apply the same principle and store them in wkt format.

OK, so add a summary of what is done and what has still to be done in the issue.

**Comment by HoucemKacem** [comment]
> OK, so add a summary of what is done and what has still to be done in the issue.

Added.

**Comment by Nevermind-s** [comment]
Any news on supporting LineString, I think it's a very important one when it comes to monitoring the traffic on the roads

**Comment by bobeal** [comment]
Hi @Nevermind-s,

Unfortunately, no news on this since we have no use-cases from our users. We can however try to prioritize it a bit if you have a need for it.
