### ISSUE TITLE
Get temporal entity evolution : if bad Link header we get a 404 when attrs query param is present

### ISSUE THREAD

**Issue by philippestoltz** [stellio-hub/stellio-context-broker#239]

**Comment by bobeal** [comment]
@HoucemKacem I'm not sure to understand this issue. 

If the link header is wrong, attrs param is expanded on default context and temporal attributes are not found in the DB. And thus, a 404 is raised, which is expected.

Do you have a different understanding?

**Comment by HoucemKacem** [comment]
> Do you have a different understanding?

I think that the 404 is expected here as you said.
