### ISSUE TITLE
Implement the discovery endpoints introduced in 1.3.1 - 5.7.5 to 5.7.10

### ISSUE THREAD

**Issue by bobeal** [stellio-hub/stellio-context-broker#268]
Discovery endpoints:

- [x] Retrieve Available Entity Types (5.7.5)
- [x] Retrieve Details of Available Entity Types (5.7.6)
- [x] Retrieve Available Entity Type Information (5.7.7)
- [ ] Retrieve Available Attributes (5.7.8)
- [ ] Retrieve Details of Available Attributes (5.7.9)
- [ ] Retrieve Available Attribute Information (5.7.10)

**Comment by bobeal** [comment]
@HoucemKacem  5.7.6 is also done, isn't it?

**Comment by HoucemKacem** [comment]
> @HoucemKacem 5.7.6 is also done, isn't it?

Yes, it is done, I updated the checklist.
