### ISSUE TITLE
Getting Bad request Error when querying the endpoint 'types/{type}' with entities containning the Attribute Location

### ISSUE THREAD

**Issue by AHABID** [stellio-hub/stellio-context-broker#315]
I'm getting a bad request error  with the endpoint 'types/{type}' when requesting entities that contains the property 'location'. It works perfectly with entities not containing this property.

The bad request error message is the following:

```
{
    "detail": "The supplied identifier was expected to be an URI but it is not: location",
    "type": "https://uri.etsi.org/ngsi-ld/errors/BadRequestData",
    "title": "The request includes input data which does not meet the requirements of the operation"
}
```

**Comment by HoucemKacem** [comment]
I think that the problem comes from [here](https://github.com/stellio-hub/stellio-context-broker/blob/develop/entity-service/src/main/kotlin/com/egm/stellio/entity/repository/Neo4jRepository.kt#L499) since it's expected to be returned in an expanded format.
