### ISSUE TITLE
Store entity payload in a dedicated table

### ISSUE THREAD

**Issue by bobeal** [stellio-hub/stellio-context-broker#35]

**Comment by HoucemKacem** [comment]
We store relationships and properties in separate columns ?

**Comment by bobeal** [comment]
> We store relationships and properties in separate columns ?

The point is that currently each entry in the temporal_entity_attribute table stores a copy of the full entity. Thus, if an entity has 10 temporal properties, we will store 10 copies of the full entity. So, the objective of this issue is to store this copy in a separated table and reference it from the temporal_entity_attribute table.

But, AFAIK, we don't need to extract properties and relationships in separate columns. Did you think about something in particular?

**Comment by HoucemKacem** [comment]
> But, AFAIK, we don't need to extract properties and relationships in separate columns. Did you think about something in particular?

No, I asked since we already have seperate properties and relationships in the expandedEntity, so if there is a need to get just one or the other it could be possible without additional processing.

**Comment by bobeal** [comment]
> No, I asked since we already have seperate properties and relationships in the expandedEntity, so if there is a need to get just one or the other it could be possible without additional processing.

Hmm, no, I don't think so ...

Currently, we only use it to render entities on a temporal query (after injecting the temporal values).

Later, we'll use them to perform the complex searches (as already did in subscription service).
