### ISSUE TITLE
Set base core context to v1.3.1

### ISSUE THREAD

**Issue by bobeal** [stellio-hub/stellio-context-broker#357]
Only filling here actions related to switching to core context v1.3.1 (instead of current v1.2.1). Not taking into account new endpoints and / or features introduced in 1.3.1 (which are / will be the subject of other issues).

- [x] Replace core context in `JsonLdUtils`
- [x] Migrate to `timeAt` / `endTimeAt` in temporal queries
- [x] Migrate to new expanded names for geo-related properties (`coordinates`, `Point`, ...)
- [x] `name` and `description` in subscriptions
- [x] `title` in error messages
- [ ] `receiverInfo` and `notifierInfo` in Endpoint datatype for subscriptions
- [ ] Update the sample Postman collection (and other used collections)
- [ ] Notify users some time before switch so that they have time to adapt
- [ ] Migrate base context in https://github.com/easy-global-market/ngsild-api-data-models: in progress in https://github.com/easy-global-market/ngsild-api-data-models/pull/98
- [ ] Migration script for existing entities : use https://schema.org/name for name and http://purl.org/dc/terms/description for description

**Comment by HoucemKacem** [comment]
We have also a `TODO : point is not part of the NGSI-LD core context`, it's now part of it ? It will have no effect on this ?
I think we should also check if there are some services communicating to Stellio using the core context.
Is there a migration note from v1.2.1 to v1.3.1  where we can find the changes of reduced/expanded terms ?

**Comment by bobeal** [comment]
> We have also a `TODO : point is not part of the NGSI-LD core context`, it's now part of it ? It will have no effect on this ?

Yes, it is listed in the TODO list above.

> I think we should also check if there are some services communicating to Stellio using the core context.

Yes, it is covered by the last point of the TODO list. 

> Is there a migration note from v1.2.1 to v1.3.1 where we can find the changes of reduced/expanded terms ?

Yes, I'll send it to you.
