### ISSUE TITLE
Align implementation of aggregated queries with the specification

### ISSUE THREAD

**Issue by bobeal** [stellio-hub/stellio-context-broker#368]
As defined in v1.4.1 of the specification:
- [x] Modify parameter names `time_bucket` and `aggregate` to align with the specification
- [x] Use ISO 8601 Duration format for aggregation periods
- [x] Better typing of attribute values to allow for specific aggregations
- [ ] Modify values of instances before aggregation depending on type
- [ ] Implement new aggregation methods
- [x] Implement possibility to have several aggregations at the same time

**Comment by gpoujol** [comment]
- [ ] Modify name time_bucket and aggregate to use the name of the spec
- [ ] Use ISO 8601 as Duration for aggregation
- [ ] Have differents types for AttributeValueType
- [ ] Modify value of instance before aggregation depending on type
- [ ] Implement new aggregate
- [ ] Imlement possibility to have several aggregation in same time

**Comment by bobeal** [comment]
> * [x]  Modify name time_bucket and aggregate to use the name of the spec
> 
>     * [x]  Use ISO 8601 as Duration for aggregation
> 
>     * [ ]  Have differents types for AttributeValueType
> 
>     * [ ]  Modify value of instance before aggregation depending on type
> 
>     * [ ]  Implement new aggregate
> 
>     * [ ]  Imlement possibility to have several aggregation in same time

moving this in the issue description.

**Comment by gpoujol** [comment]
> > * [x]   Modify name time_bucket and aggregate to use the name of the spec
> >   
> >   * [x]   Use ISO 8601 as Duration for aggregation
> >   * [ ]   Have differents types for AttributeValueType
> >   * [ ]   Modify value of instance before aggregation depending on type
> >   * [ ]   Implement new aggregate
> >   * [ ]   Imlement possibility to have several aggregation in same time
> 
> moving this in the issue description.

You already did it ?
