### ISSUE TITLE
Internal error when BadRequest exception occurs

### ISSUE THREAD

**Issue by vraybaud** [stellio-hub/stellio-context-broker#41]
When doing that request :

POST /ngsi-ld/v1/entities HTTP/1.1
```json
{
  "id": "urn:ngsi-ld:Vehicle:A12388",
  "type": "Vehicle",
  "speed": {
    "type": "Property"
  },
  "@context": [
    "https://raw.githubusercontent.com/easy-global-market/ngsild-api-data-models/master/shared-jsonld-contexts/egm.jsonld",
    "https://raw.githubusercontent.com/easy-global-market/ngsild-api-data-models/master/aquac/jsonld-contexts/aquac.jsonld",
    "http://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context.jsonld"
  ]
}
```

The response should be an error BadRequestData (400 http) like that, helping the user figure out what's wrong in the request :
```json
{
    "detail": "Key $NGSILD _PROPERTY_VALUE not found in $propertyValues").
    "type": "https://uri.etsi.org/ngsi-ld/errors/BadRequestData",
    "title": "The request includes input data which does not meet the requirements of the operation"
}
```

But today we get this : (500 http)
```json
{
    "detail": "There has been an error during the operation execution",
    "type": "https://uri.etsi.org/ngsi-ld/errors/InternalError",
    "title": "There has been an error during the operation execution"
}
```

**Investigation :**
This happens because the error occurs in a function with @Transactional annotation which seems to not pass correctly the exception.

**Comment by bobeal** [comment]
Indeed, current code in ``NgsiLdParsingUtils` is not totally bulletproof (in other words, it expects a value and crashes miserably if none is found).

A refactoring has been started to improve validation and type safety (cf for instance `ExpandedEntity` in shared lib). 

We'll talk about it soon for the next steps.

**Comment by vraybaud** [comment]
Found a related issue : https://github.com/spring-projects/spring-framework/issues/22412

**Comment by vraybaud** [comment]
Also another bug somehow close to this issue : 
@Transactional() alone in kt only rollbacks the transaction for unchecked Exceptions
It should be modified to 
    @Transactional(rollbackFor = [BadRequestDataException::class])
for example to do a rollback for the given exceptions.

Is it an expected behaviour to not do a rollback for transactions leading to BadRequestDataException?
