### ISSUE TITLE
Returned message not pointing to the right cause of the error

### ISSUE THREAD

**Issue by AHABID** [stellio-hub/stellio-context-broker#440]
When querying the temporal evolution of an entity with a non-existing attribute as value of the `attrs ` paramter, we are getting this kind of error message as response:

```
{
    "detail": "Entity <EntityID> was not found",
    "type": "https://uri.etsi.org/ngsi-ld/errors/ResourceNotFound",
    "title": "The referred resource has not been found"
}
```

However, the `attrs `  parameter is the wrong  and the entity exists. This is making some misunderstanding of cause of the problem.

**Comment by bobeal** [comment]
This is happening here: https://github.com/stellio-hub/stellio-context-broker/blob/develop/search-service/src/main/kotlin/com/egm/stellio/search/service/QueryService.kt#L48-L53

Difficult to say what is missing between the entity and the requested attributes without adding an extra DB call.

Does a message saying that the entity or the requested attributes do not exist would good enough?

**Comment by AHABID** [comment]
Yes. At least to show all eventual possible causes in the error message.
Maybe Here [https://github.com/stellio-hub/stellio-context-broker/blob/develop/shared/src/main/kotlin/com/egm/stellio/shared/util/ApiResponses.kt](https://github.com/stellio-hub/stellio-context-broker/blob/develop/shared/src/main/kotlin/com/egm/stellio/shared/util/ApiResponses.kt ) to add a new method such as  `entityOrAttributesNotFoundMessage`.
