### ISSUE TITLE
Query entities by attrs only is retrieving nothing

### ISSUE THREAD

**Issue by junjou** [stellio-hub/stellio-context-broker#452]
Using this endpoint to retrieve all entities having the `flow` attribute:  
`/ngsi-ld/v1/entities?attrs=flow`
is retrieving an empty array

While adding an idPattern seems to make it work properly:
`/ngsi-ld/v1/entities?attrs=flow&idPattern=(?i).*River.*`
is retrieving all entities having a `flow` attribute and containing "river" within their id

**Comment by bobeal** [comment]
Indeed, the `attrs` query parameter is currently only used for the representation of the results, and not to select the entities that should be part of the result (but it should, as per the specification).
