### ISSUE TITLE
Finish implementation of HTTP response common requirements (6.3.6)

### ISSUE THREAD

**Issue by bobeal** [stellio-hub/stellio-context-broker#52]
The content type of the response is well set on most responses.

However it has still be implemented in some queries (e.g. search on entities or list of subscriptions that return a `text/plain` content type)

**Comment by HoucemKacem** [comment]
I'm wondering if you could send me a reference (since I couldn't find it in the spec)

**Comment by bobeal** [comment]
> I'm wondering if you could send me a reference (since I couldn't find it in the spec)

The reference is in the subject: 6.3.6 (and the first sentence: `Implementations shall honour the Accept header provided by HTTP requests`, which is the purpose of the Accept header)

**Comment by HoucemKacem** [comment]
From what I understood from the 6.3.6:
We should check the accept header provided with the request.
If is 'application/json'  we return the context in the response link header and 'application/json' as response content type.  
If is 'application/ld+json'  we return the context in the response payload and 'application/ld+json' as response content type.
I don't understand the text/plain content type and when it should be returned.

**Comment by bobeal** [comment]
Was not able to reproduce this text/plain content type in the response, closing this issue.

**Comment by bobeal** [comment]
Reopened because we effectively do not manage yet the Accept header as expected by the spec.
