### ISSUE TITLE
observedAt= modifiedAt when not mentioned

### ISSUE THREAD

**Issue by hlange** [stellio-hub/stellio-context-broker#536]
Hi,
I was looking in the documentation for NGSI-LD but couldn't find anything.

I would have assumed, if a value is generated or changed and the observatedAt was not defined, it would use the current timestamp of the server. However, when I simply change the temperature of a beehive the temperature is changing, however the observedAt is not. If I look at the temporal interface no new entry was generated for the changed temperature. When I define observedAt at the update, than a new entry exist with the timestamp that I defined.

At https://ngsi-ld-tutorials.readthedocs.io/en/latest/iot-agent-json.html#update-a-provisioned-device observedAt was defined as "The observedAt shows last the time any command associated with the entity has been invoked. "

So my suggestion is that if observedAt was not mentioned at patch, the server time is used.

**Comment by bobeal** [comment]
Hi @hlange,

Indeed, currently, we are only adding a new entry in the temporal interface if an `observedAt` has been provided, but we plan to extend this soon to track the temporal history of any attribute (using `modifiedAt`, which is indeed generated by the server, if no `observedAt` is present).

Hope this clarifies your question?

**Comment by bobeal** [comment]
`modifiedAt` (and `createdAt`) is now supported (see #580).
