### ISSUE TITLE
Migrate and update the quick guide

### ISSUE THREAD

**Issue by bobeal** [stellio-hub/stellio-context-broker#57]
Currently, the quick guide referenced in the README.md points to the one located in https://github.com/easy-global-market/ngsild-api-data-models.

This is prone to error as we may (and we did!) forget to update it when there are changes to the API and is also confusing for users that have to jump to another site to quick start using the project.

So the purpose of this issue is to bootstrap a new quick guide in this repository, with samples data in a `samples` directory, based on beekeeping data model.

Make something oriented like a real use-case (and not a showcase of requests like the existing one). For instance:
- Create context information (beekeeper, beehive, ...), atomic and / or in batch
- Perform 2 or 3 simple queries
- Create a subscription on update to values of properties of a beehive (and explain how to get notified)
- Update values of properties of a beehive
- Query the temporal evolution of the properties of a beehive

**Comment by HoucemKacem** [comment]
I did a first version of the API Quick guide.
In the last query in the API Use case part (Get the temporal evolution of the beeHive properties), if i  set time==2019-02-01T12:00:00Z for example, the API returns 500 with the following detail

`class java.time.OffsetDateTime cannot be cast to class java.time.ZonedDateTime (java.time.OffsetDateTime and java.time.ZonedDateTime are in module java.base of loader 'bootstrap')   
`

**Comment by bobeal** [comment]
> In the last query in the API Use case part (Get the temporal evolution of the beeHive properties), if i set time==2019-02-01T12:00:00Z for example, the API returns 500 with the following detail

On a new installation? On the integration platform? ...

**Comment by HoucemKacem** [comment]
On the dev platform.
I used the dev platform to create (test) the use case scenario.

**Comment by bobeal** [comment]
> On the dev platform.
> I used the dev platform to create (test) the use case scenario.

OK, so I guess it is related to #1 ? Investigate and fix it.
