### ISSUE TITLE
Querying Entities API

### ISSUE THREAD

**Issue by vicanfon** [stellio-hub/stellio-context-broker#582]
I want to query all the entities I have registered but "http://localhost:8080/ngsi-ld/v1/entities" doesn't do the trick.

Do you know how to do it?

I am missing from a more extensive documentation on the API and querying itself.

Thanks,

**Comment by bobeal** [comment]
Hi,

Indeed, you can't do such a "wide" query and have to provide at least some parameters.

You can find the full details in the NGSI-LD API specification (which the Stellio context broker is implementing - yet not fully) : https://www.etsi.org/deliver/etsi_gs/CIM/001_099/009/01.05.01_60/gs_CIM009v010501p.pdf. And in particular for this specific point, you can have a look at section 6.4.3.2.

**Comment by vicanfon** [comment]
Thanks for the link
