### ISSUE TITLE
Subscription on a Multi-Instance Attribute

### ISSUE THREAD

**Issue by AHABID** [stellio-hub/stellio-context-broker#637]
We have tried to create a subscription on a specific instance of a property using the NGSI-LD query language as follow:

`"q":"propertyName.datasetId==\"urn:ngsi-ld:Dataset:01\""`

The subscription is created, but when updating the concerned instance of the attribute we are not reciving any notification. On the subscription entity the "timesSent" is 0 .

**Comment by bobeal** [comment]
Until #1144 is done, this can be achieved by specifying instead:

```
"q":"propertyName.datasetId==urn:ngsi-ld:Dataset:01"
```
