### ISSUE TITLE
Unable to start Stellio Docker-in-Docker

### ISSUE THREAD

**Issue by jason-fox** [stellio-hub/stellio-context-broker#661]
When testing the existing Stellio docker-compose via GitHub Actions, the subscription-service is unable to start - see: https://github.com/FIWARE/tutorials.Linked-Data/runs/6507040721

```text
ERROR: for stellio-subscription-service  Cannot start service subscription-service: driver failed programming external connectivity on endpoint stellio-subscription-service (e977bc20cee90e0db7ef7dcd7f6b1a7c120bd4502b983ccc6eb3341ba2b0d3df): Error starting userland proxy: listen tcp4 0.0.0.0:8084: bind: address already in use
```

I don't think this is necessarily a Stellio issue, my guess is that it is most likely due to [Mono](https://github.com/actions/virtual-environments/issues/2821) running on the same port, however altering the config to use a different port or adding a comment within the docker-compose explaining potential Docker-in-Docker issues would probably help.

**Comment by bobeal** [comment]
Ports are documented in https://github.com/stellio-hub/stellio-context-broker#quick-start and the error message is quite clear about the problem.
