### ISSUE TITLE
Relationship is automatically deleted from entity payload when its target entity is deleted

### ISSUE THREAD

**Issue by AHABID** [stellio-hub/stellio-context-broker#699]
Let's suppose that we have 2 entities _A_ and _B_, where entity _A_ have a relationship attribute targeting the entity _B_.

If entity _B_ is deleted, we notice that the entity _A_ is automatically modified by deleting the relationship targeting the entity _B_.

**Comment by bobeal** [comment]
Fixed in 6520885944f933910682c3ebfdf613be1f9e9b19
