### ISSUE TITLE
add postman collection for quick guide

### ISSUE THREAD

**Issue by vraybaud** [stellio-hub/stellio-context-broker#73]
Following discussion in PR #68 : https://github.com/stellio-hub/stellio-context-broker/pull/68#issuecomment-644698120
We agreed to have a postman collection for this guide to help users not used to cli.

**Comment by HoucemKacem** [comment]
A collection was created.
It can be imported with the following link:
https://www.getpostman.com/collections/a8d09cb6dbf352774eec

**Comment by bobeal** [comment]
> A collection was created.
> It can be imported with the following link:
> https://www.getpostman.com/collections/a8d09cb6dbf352774eec

Add it in the project and add a reference in the quick guide.
