### ISSUE TITLE
Add creation and modification dates when "Add attributes to Temporal Representation of Entity" endpoint is used

### ISSUE THREAD

**Issue by gpoujol** [stellio-hub/stellio-context-broker#782]
When temporal history is added through the "Add attributes to Temporal Representation of Entity" endpoint the creation and modification date is not added. 

So when a time request is made these two attribut are not present.

**Comment by bobeal** [comment]
- Inject creation and modification dates for the newly added attributes
- Update modification date for the entity

**Comment by gpoujol** [comment]
Looking at this issue. I did some tests. I created an entity and added an instance on my attribute. Then I patched my entity. I expected to have 3 instances of my attributes (creation, added, patch) but I ended up with only 1 single instance. 
It happens when we do the `deleteTemporalAttributeReference`. Here `https://github.com/stellio-hub/stellio-context-broker/blob/099a9827319485201755ae82edaff0ff55bad412/search-service/src/main/kotlin/com/egm/stellio/search/service/TemporalEntityAttributeService.kt#L243`.

I don't why this request delete also row in table attribute_instance. Do you have idea ? It's a normal behavior? @bobeal

**Comment by bobeal** [comment]
> Looking at this issue. I did some tests. I created an entity and added an instance on my attribute. Then I patched my entity. I expected to have 3 instances of my attributes (creation, added, patch) but I ended up with only 1 single instance. It happens when we do the `deleteTemporalAttributeReference`. Here `https://github.com/stellio-hub/stellio-context-broker/blob/099a9827319485201755ae82edaff0ff55bad412/search-service/src/main/kotlin/com/egm/stellio/search/service/TemporalEntityAttributeService.kt#L243`.
> 
> I don't why this request delete also row in table attribute_instance. Do you have idea ? It's a normal behavior? @bobeal

which request exactly? this is not clear as "patched" can be 2 endpoints actually. and I don't understand why you are "patching" the entity after adding attribute instances. 

please give more details about the requests and what are trying to achieve (actually I don't really get the link with the object of the issue).

**Comment by gpoujol** [comment]
When I do a PATCH with `updateEntityAttributes` or a POST with  `appendEntityAttributes`.

I patch entity after adding attributes instances to check if I have on an instance the creation/modification date and for the other nothing.

I just want to understand how works both request doing tests and looking at the codes in the same time.

I think you are right it has nothing to do with this issue. Maybe create a new one for this case ?

**Comment by bobeal** [comment]
> I think you are right it has nothing to do with this issue. Maybe create a new one for this case ?

Done in #788

**Comment by bobeal** [comment]
Since that time, it has been refactored and the endpoint now uses the `upsertAttributes` function in `EntityPayloadService` (https://github.com/stellio-hub/stellio-context-broker/blob/develop/search-service/src/main/kotlin/com/egm/stellio/search/service/EntityPayloadService.kt#L574), which does the expected job.
