### ISSUE TITLE
Add possibility to get a specific observedAt

### ISSUE THREAD

**Issue by gasserluc** [stellio-hub/stellio-context-broker#807]
To be able to a query like time=2022-12-01T06:38:00Z or q=attributeName.observedAt=="2022-12-01T06:38:00Z" instead of having to do timerel=between&timeAt=2022-12-01T06:37:00Z&endTimeAt=2022-12-01T06:39:00Z

**Comment by bobeal** [comment]
#869 will allow this... only if `2022-12-01T06:38:00Z` is the current value of the `observedAt` property of `attributeName`. If you are searching for values in the history of your entity, you will still have to use the temporal API as now.
