### ISSUE TITLE
Review and update the samples in the "API Walkthrough" page on RTD

### ISSUE THREAD

**Issue by bobeal** [stellio-hub/stellio-context-broker#902]
It has been reported that the temporal queries have not been updated to NGSI-LD Core Context v1.3+ (`time` vs `timeAt`, ...).

Take this opportunity to review all the queries and be sure they are all still correct.

**Comment by bobeal** [comment]
@gpoujol I think it can be closed?

**Comment by gpoujol** [comment]
> @gpoujol I think it can be closed?

Yes I close it
