### ISSUE TITLE
have some methods available to use for health check of the services

### ISSUE THREAD

**Issue by agaldemas-eridanis** [stellio-hub/stellio-context-broker#929]
Hello, 
to be able to configure some http (or tcp) probes under **kubernetes** (readinessProbe, livenessProbe), we need some **non functional** api method returning a 200 status... 

Should it be poossible you add a special method to call that allows to check that the containers inside the pods are working ok, by returning a 200 status, 

Something like `/version` method of Orion, that return some information about the software version and the uptime, such as :
```
curl http://localhost:8080/version
{
"stellio-api-gateway" : {
  "version" : "2.4.0",
  "uptime" : "54 d, 0 h, 28 m, 34 s",
  "git_hash" : "......",
  "compile_time" : "Thu Dec 22 17:48:15 UTC 2022",
  "release_date" : "Thu Dec 22 17:48:15 UTC 2022",
  "machine" : "x86_64",
  "doc" : "...",
  "libversions": {
     ...
  }
}
````
This for the 3 deployments: `search-service`, `subscription-service` and `api-gateway`.

**Comment by agaldemas-eridanis** [comment]
note that this is also useful for docker deployment

**Comment by bobeal** [comment]
Hi @agaldemas-eridanis,

You can use the health endpoint. You'll find some info in https://stellio.readthedocs.io/en/latest/admin/monitoring_and_logging.html

**Comment by agaldemas-eridanis** [comment]
OK, thanks @bobeal (RTFM;O)
